version: 2.1

docker_context: &docker_context
  context:
    - Leddzip Dockerhub

master_filter: &master_filter
  filters:
    branches:
      only: master

jobs:
  build-test-and-push:
    machine:
      image: ubuntu-2204:2022.10.2
    parameters:
      env:
        type: string
    steps:
      - checkout
      - run: |
          export ENV_TARGET=<<parameters.env>>
          make generate-dockerfile
          echo "$MY_CIRCLECI_DOCKERHUB_PASSWORD" | docker login --username $MY_CIRCLECI_DOCKERHUB_USERNAME --password-stdin
          make docker-build
      - run: |
          docker run --rm -v $(pwd)/test:/workdir leddzip/bash-packer-aws:latest packer validate packer.json >> test_output.txt
          cmp test_output.txt test/expected_output.txt
          docker run --rm leddzip/bash-packer-aws:latest packer --version
          docker run --rm leddzip/bash/packer-aws:latest aws --version
      - run: |
          make docker-push

  "Build production":
    jobs:
      - build-test-and-push:
          <<: *docker_context
          <<: *master_filter
          env: prod


